services:
  # payload:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - ENV_FILE=.env.docker
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - payload-public:/app/public
  #   networks:
  #     - app-network
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #   environment:
  #     - NODE_ENV=production
  #   env_file: .env.docker

  worker-redwood:
    profiles:
      - redwood-worker
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    restart: always
    volumes:
      - payload-public:/app/public
    networks:
      - app-network
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DOCKER_DATABASE_URI:-mongodb://mongo:27017/cvx-junior-golf}
    env_file: .env

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app-network

volumes:
  mongo-data:
  payload-public:

networks:
  app-network:
    driver: bridge
