services:
  web:
    image: mikecebul/drug-test-mi:branch-test
    pull_policy: always
    restart: always
    ports:
      - 3000
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    networks:
      - dokploy-network

  worker-redwood:
    image: mikecebul/drug-test-mi:branch-test-worker
    pull_policy: always
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
