export const REDWOOD_SKIP_HEADSHOT_PUSH_CONTEXT_KEY = 'skipRedwoodHeadshotPush'
export const REDWOOD_SKIP_CLIENT_UPDATE_QUEUE_CONTEXT_KEY = 'skipRedwoodClientUpdateQueue'
export const REDWOOD_APPROVED_CLIENT_UPDATE_FIELDS_CONTEXT_KEY = 'approvedRedwoodClientUpdateFields'
